name: Compile Thermostat Firmware

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build with PlatformIO
        run: pio run -e lolin_c3_pico

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thermostat-firmware
          path: .pio/build/lolin_c3_pico/*.bin
